artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/b2f52fbfadc04de4bdcdb2b1bdead2e7/artifacts
end_time: 1743616050795
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: b2f52fbfadc04de4bdcdb2b1bdead2e7
run_name: righteous-lynx-767
run_uuid: b2f52fbfadc04de4bdcdb2b1bdead2e7
source_name: ''
source_type: 4
source_version: ''
start_time: 1743616046821
status: 3
tags: []
user_id: evankellener
