artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/0b5a4ee3aeb549ae8442efed0bfc363e/artifacts
end_time: 1743980664948
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 0b5a4ee3aeb549ae8442efed0bfc363e
run_name: magnificent-foal-220
run_uuid: 0b5a4ee3aeb549ae8442efed0bfc363e
source_name: ''
source_type: 4
source_version: ''
start_time: 1743980660762
status: 3
tags: []
user_id: evankellener
