artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/d50d76fcf3b44ee0a963ff4bd2b7f00e/artifacts
end_time: 1744052034430
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: d50d76fcf3b44ee0a963ff4bd2b7f00e
run_name: illustrious-roo-296
run_uuid: d50d76fcf3b44ee0a963ff4bd2b7f00e
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052027421
status: 3
tags: []
user_id: evankellener
