artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/f6fc7c8caa284b838b8e9ef60e0bce1a/artifacts
end_time: 1743528347436
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: f6fc7c8caa284b838b8e9ef60e0bce1a
run_name: powerful-dog-231
run_uuid: f6fc7c8caa284b838b8e9ef60e0bce1a
source_name: ''
source_type: 4
source_version: ''
start_time: 1743528345291
status: 3
tags: []
user_id: evankellener
