artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/7ca8e45c75da49d0adb3babcf72a8876/artifacts
end_time: 1743534781313
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 7ca8e45c75da49d0adb3babcf72a8876
run_name: kindly-owl-991
run_uuid: 7ca8e45c75da49d0adb3babcf72a8876
source_name: ''
source_type: 4
source_version: ''
start_time: 1743534778866
status: 3
tags: []
user_id: evankellener
