artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/0a8e80f82d3d4bb9b1e5a3a1f30d1e7e/artifacts
end_time: 1746420502741
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 0a8e80f82d3d4bb9b1e5a3a1f30d1e7e
run_name: incongruous-cat-698
run_uuid: 0a8e80f82d3d4bb9b1e5a3a1f30d1e7e
source_name: ''
source_type: 4
source_version: ''
start_time: 1746420496206
status: 3
tags: []
user_id: evankellener
