artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/b8fe026bbc824adaa4e0ab0d4cd3409a/artifacts
end_time: 1747937378104
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: b8fe026bbc824adaa4e0ab0d4cd3409a
run_name: sneaky-bear-933
run_uuid: b8fe026bbc824adaa4e0ab0d4cd3409a
source_name: ''
source_type: 4
source_version: ''
start_time: 1747937362029
status: 3
tags: []
user_id: evankellener
