artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/a055cbfcaaf4429bb0f65fcde32c95c5/artifacts
end_time: 1743534754284
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: a055cbfcaaf4429bb0f65fcde32c95c5
run_name: trusting-chimp-285
run_uuid: a055cbfcaaf4429bb0f65fcde32c95c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1743534746710
status: 3
tags: []
user_id: evankellener
