artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/ed94f04aa5f54733a7a16cf4cbebe3c3/artifacts
end_time: 1743615858649
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: ed94f04aa5f54733a7a16cf4cbebe3c3
run_name: intrigued-loon-863
run_uuid: ed94f04aa5f54733a7a16cf4cbebe3c3
source_name: ''
source_type: 4
source_version: ''
start_time: 1743615856202
status: 3
tags: []
user_id: evankellener
