artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/3f6c1dd8cfef44fd882ccf8f3319ab8e/artifacts
end_time: 1743977721918
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 3f6c1dd8cfef44fd882ccf8f3319ab8e
run_name: entertaining-ape-728
run_uuid: 3f6c1dd8cfef44fd882ccf8f3319ab8e
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977715278
status: 3
tags: []
user_id: evankellener
