artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/baf3d6287e484accbe54c1ad83dce07c/artifacts
end_time: 1743615890180
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: baf3d6287e484accbe54c1ad83dce07c
run_name: illustrious-roo-296
run_uuid: baf3d6287e484accbe54c1ad83dce07c
source_name: ''
source_type: 4
source_version: ''
start_time: 1743615887935
status: 3
tags: []
user_id: evankellener
