artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/d1dfcebfe91e4558b6fa7136d0edc6cf/artifacts
end_time: 1743977579806
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: d1dfcebfe91e4558b6fa7136d0edc6cf
run_name: big-swan-262
run_uuid: d1dfcebfe91e4558b6fa7136d0edc6cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977572711
status: 3
tags: []
user_id: evankellener
