artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/49f3dacdf3e94c1fb8fc177d8cdfb66a/artifacts
end_time: 1743615958503
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 49f3dacdf3e94c1fb8fc177d8cdfb66a
run_name: powerful-dog-231
run_uuid: 49f3dacdf3e94c1fb8fc177d8cdfb66a
source_name: ''
source_type: 4
source_version: ''
start_time: 1743615956488
status: 3
tags: []
user_id: evankellener
