artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/54a82acdef31403cb96ef70ceb8e1ba0/artifacts
end_time: 1746641481870
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 54a82acdef31403cb96ef70ceb8e1ba0
run_name: enchanting-crab-61
run_uuid: 54a82acdef31403cb96ef70ceb8e1ba0
source_name: ''
source_type: 4
source_version: ''
start_time: 1746641475684
status: 3
tags: []
user_id: evankellener
