artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/5e0caebddd06487db6ade66ff71a837c/artifacts
end_time: 1746727488515
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 5e0caebddd06487db6ade66ff71a837c
run_name: brawny-fish-813
run_uuid: 5e0caebddd06487db6ade66ff71a837c
source_name: ''
source_type: 4
source_version: ''
start_time: 1746727479115
status: 3
tags: []
user_id: evankellener
