artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/20aacb1ce0014fd2bca29c30b6dfcb3f/artifacts
end_time: 1746420607926
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 20aacb1ce0014fd2bca29c30b6dfcb3f
run_name: overjoyed-bear-140
run_uuid: 20aacb1ce0014fd2bca29c30b6dfcb3f
source_name: ''
source_type: 4
source_version: ''
start_time: 1746420592124
status: 3
tags: []
user_id: evankellener
