artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/babbc12d34cd4dae984ac9617aaf3600/artifacts
end_time: 1743534601907
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: babbc12d34cd4dae984ac9617aaf3600
run_name: handsome-stork-978
run_uuid: babbc12d34cd4dae984ac9617aaf3600
source_name: ''
source_type: 4
source_version: ''
start_time: 1743534595402
status: 3
tags: []
user_id: evankellener
