artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/ed62b55c0e754f8a8f887f059cdfbaea/artifacts
end_time: 1745605147046
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: ed62b55c0e754f8a8f887f059cdfbaea
run_name: thoughtful-wren-332
run_uuid: ed62b55c0e754f8a8f887f059cdfbaea
source_name: ''
source_type: 4
source_version: ''
start_time: 1745605143294
status: 3
tags: []
user_id: evankellener
