artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/f01b60aaee884eb7bebf549cbe5ec06a/artifacts
end_time: 1746420675159
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: f01b60aaee884eb7bebf549cbe5ec06a
run_name: kindly-owl-991
run_uuid: f01b60aaee884eb7bebf549cbe5ec06a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746420667318
status: 3
tags: []
user_id: evankellener
