artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/b22a48def30b4e71a96d5ac998dd8daa/artifacts
end_time: 1743980470382
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: b22a48def30b4e71a96d5ac998dd8daa
run_name: intrigued-loon-863
run_uuid: b22a48def30b4e71a96d5ac998dd8daa
source_name: ''
source_type: 4
source_version: ''
start_time: 1743980467314
status: 3
tags: []
user_id: evankellener
