artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/1bfae6c45d144e3aac64718b29da2ffc/artifacts
end_time: 1745605234319
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 1bfae6c45d144e3aac64718b29da2ffc
run_name: fortunate-midge-41
run_uuid: 1bfae6c45d144e3aac64718b29da2ffc
source_name: ''
source_type: 4
source_version: ''
start_time: 1745605228743
status: 3
tags: []
user_id: evankellener
