artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/b4b05ce1ad474b1eba5f8bfe62777f34/artifacts
end_time: 1743534668031
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: b4b05ce1ad474b1eba5f8bfe62777f34
run_name: enchanting-crab-61
run_uuid: b4b05ce1ad474b1eba5f8bfe62777f34
source_name: ''
source_type: 4
source_version: ''
start_time: 1743534665487
status: 3
tags: []
user_id: evankellener
