artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/36a1b4c1508343fbadeb216d1bfbd9bc/artifacts
end_time: 1746727135948
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 36a1b4c1508343fbadeb216d1bfbd9bc
run_name: amazing-lark-886
run_uuid: 36a1b4c1508343fbadeb216d1bfbd9bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1746727133572
status: 3
tags: []
user_id: evankellener
