artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/c2fa9af8760c4170bdb4ae36effae827/artifacts
end_time: 1743534641855
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: c2fa9af8760c4170bdb4ae36effae827
run_name: wise-sheep-839
run_uuid: c2fa9af8760c4170bdb4ae36effae827
source_name: ''
source_type: 4
source_version: ''
start_time: 1743534639280
status: 3
tags: []
user_id: evankellener
