artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/1d9edb6c2a4e4499a2c7d956baf2aa3d/artifacts
end_time: 1744052064020
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 1d9edb6c2a4e4499a2c7d956baf2aa3d
run_name: salty-swan-65
run_uuid: 1d9edb6c2a4e4499a2c7d956baf2aa3d
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052057609
status: 3
tags: []
user_id: evankellener
