artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/d2bacc78efca4bb192de1f6c8bcbb35d/artifacts
end_time: 1744052471609
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: d2bacc78efca4bb192de1f6c8bcbb35d
run_name: sneaky-bear-933
run_uuid: d2bacc78efca4bb192de1f6c8bcbb35d
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052462721
status: 3
tags: []
user_id: evankellener
