artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/18ae0126bcb14dd0ae66e5cc0a549dbe/artifacts
end_time: 1746729596204
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 18ae0126bcb14dd0ae66e5cc0a549dbe
run_name: wise-sheep-839
run_uuid: 18ae0126bcb14dd0ae66e5cc0a549dbe
source_name: ''
source_type: 4
source_version: ''
start_time: 1746729593420
status: 3
tags: []
user_id: evankellener
