artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/1ac98a53a9fc42eeac4d6219ba5d91fd/artifacts
end_time: 1748497412305
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 1ac98a53a9fc42eeac4d6219ba5d91fd
run_name: incongruous-hare-938
run_uuid: 1ac98a53a9fc42eeac4d6219ba5d91fd
source_name: ''
source_type: 4
source_version: ''
start_time: 1748497395983
status: 3
tags: []
user_id: evankellener
