artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/b61a75a9afdc44b7b71ead8c8a4abb76/artifacts
end_time: 1747943347753
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: b61a75a9afdc44b7b71ead8c8a4abb76
run_name: dashing-squid-561
run_uuid: b61a75a9afdc44b7b71ead8c8a4abb76
source_name: ''
source_type: 4
source_version: ''
start_time: 1747943339262
status: 3
tags: []
user_id: evankellener
