artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/fdce2b0e5f4a4e0ea15f6df0ce00b62d/artifacts
end_time: 1744052145144
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: fdce2b0e5f4a4e0ea15f6df0ce00b62d
run_name: nimble-asp-76
run_uuid: fdce2b0e5f4a4e0ea15f6df0ce00b62d
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052132207
status: 3
tags: []
user_id: evankellener
