artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/02bcff84bdb949aca9fe40fac7b8ee30/artifacts
end_time: 1744052045729
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 02bcff84bdb949aca9fe40fac7b8ee30
run_name: nervous-snipe-157
run_uuid: 02bcff84bdb949aca9fe40fac7b8ee30
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052034517
status: 3
tags: []
user_id: evankellener
