artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/cdf2c7719d9c41ba9c934edae26fa10d/artifacts
end_time: 1746648650932
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: cdf2c7719d9c41ba9c934edae26fa10d
run_name: exultant-duck-612
run_uuid: cdf2c7719d9c41ba9c934edae26fa10d
source_name: ''
source_type: 4
source_version: ''
start_time: 1746648641453
status: 3
tags: []
user_id: evankellener
