artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/b7cca68afdd44889baeb20dabf2924f5/artifacts
end_time: 1743977630350
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: b7cca68afdd44889baeb20dabf2924f5
run_name: incongruous-hare-938
run_uuid: b7cca68afdd44889baeb20dabf2924f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977621767
status: 3
tags: []
user_id: evankellener
