artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/ac8ede8485e949ac9dc11b7b5adbae9a/artifacts
end_time: 1746648716437
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: ac8ede8485e949ac9dc11b7b5adbae9a
run_name: funny-lynx-488
run_uuid: ac8ede8485e949ac9dc11b7b5adbae9a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746648713851
status: 3
tags: []
user_id: evankellener
