artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/e9deca82f0104cb78dcca3b416ffb671/artifacts
end_time: 1743978097402
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: e9deca82f0104cb78dcca3b416ffb671
run_name: righteous-lynx-767
run_uuid: e9deca82f0104cb78dcca3b416ffb671
source_name: ''
source_type: 4
source_version: ''
start_time: 1743978094161
status: 3
tags: []
user_id: evankellener
