artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/e2af572bd4c44c6c9dbd4cc9cd15e264/artifacts
end_time: 1747937361908
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: e2af572bd4c44c6c9dbd4cc9cd15e264
run_name: righteous-lynx-767
run_uuid: e2af572bd4c44c6c9dbd4cc9cd15e264
source_name: ''
source_type: 4
source_version: ''
start_time: 1747937355713
status: 3
tags: []
user_id: evankellener
