artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/8c18ed8c8bce4c06815ca5aff4a5e814/artifacts
end_time: 1746420262438
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 8c18ed8c8bce4c06815ca5aff4a5e814
run_name: thoughtful-wren-332
run_uuid: 8c18ed8c8bce4c06815ca5aff4a5e814
source_name: ''
source_type: 4
source_version: ''
start_time: 1746420251954
status: 3
tags: []
user_id: evankellener
