artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/563d2ce25f6b44da859dbb4dff7ec02e/artifacts
end_time: 1746048101444
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 563d2ce25f6b44da859dbb4dff7ec02e
run_name: intrigued-loon-863
run_uuid: 563d2ce25f6b44da859dbb4dff7ec02e
source_name: ''
source_type: 4
source_version: ''
start_time: 1746047889906
status: 3
tags: []
user_id: evankellener
