artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/d36ddda481fa4943a77ebe4b32fdecd6/artifacts
end_time: 1743528312372
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: d36ddda481fa4943a77ebe4b32fdecd6
run_name: traveling-perch-61
run_uuid: d36ddda481fa4943a77ebe4b32fdecd6
source_name: ''
source_type: 4
source_version: ''
start_time: 1743528307781
status: 3
tags: []
user_id: evankellener
