artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/7f6a0f2a85a947b9b2badda48a9ebf32/artifacts
end_time: 1745605164092
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 7f6a0f2a85a947b9b2badda48a9ebf32
run_name: salty-swan-65
run_uuid: 7f6a0f2a85a947b9b2badda48a9ebf32
source_name: ''
source_type: 4
source_version: ''
start_time: 1745605147150
status: 3
tags: []
user_id: evankellener
