artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/0d8aee41ccb6481fbf53fb0d9cf1983a/artifacts
end_time: 1746641469334
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 0d8aee41ccb6481fbf53fb0d9cf1983a
run_name: nimble-asp-76
run_uuid: 0d8aee41ccb6481fbf53fb0d9cf1983a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746641467211
status: 3
tags: []
user_id: evankellener
