artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/39a5c090a9e14ed386edfaa5b939ccba/artifacts
end_time: 1743542290660
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 39a5c090a9e14ed386edfaa5b939ccba
run_name: funny-lynx-488
run_uuid: 39a5c090a9e14ed386edfaa5b939ccba
source_name: ''
source_type: 4
source_version: ''
start_time: 1743542288092
status: 3
tags: []
user_id: evankellener
