artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/dd83cddfc42e4917b67d6fa663dd9aa7/artifacts
end_time: 1743542143887
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: dd83cddfc42e4917b67d6fa663dd9aa7
run_name: grandiose-hog-939
run_uuid: dd83cddfc42e4917b67d6fa663dd9aa7
source_name: ''
source_type: 4
source_version: ''
start_time: 1743542142658
status: 3
tags: []
user_id: evankellener
