artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/43f3f62a585e4a02bc2c3a4cffa53aab/artifacts
end_time: 1743623577139
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 43f3f62a585e4a02bc2c3a4cffa53aab
run_name: respected-smelt-895
run_uuid: 43f3f62a585e4a02bc2c3a4cffa53aab
source_name: ''
source_type: 4
source_version: ''
start_time: 1743623566789
status: 3
tags: []
user_id: evankellener
