artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/6bfac87cf3b846da9e03dfd74831cdd1/artifacts
end_time: 1743528295255
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 6bfac87cf3b846da9e03dfd74831cdd1
run_name: nervous-snipe-157
run_uuid: 6bfac87cf3b846da9e03dfd74831cdd1
source_name: ''
source_type: 4
source_version: ''
start_time: 1743528284808
status: 3
tags: []
user_id: evankellener
