artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/754cdbcc52934ad8bcd6baaac7f7554e/artifacts
end_time: 1746729674864
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 754cdbcc52934ad8bcd6baaac7f7554e
run_name: big-swan-262
run_uuid: 754cdbcc52934ad8bcd6baaac7f7554e
source_name: ''
source_type: 4
source_version: ''
start_time: 1746729669892
status: 3
tags: []
user_id: evankellener
