artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/6aca393d3c804fa3aac0aeaf87d4c289/artifacts
end_time: 1746648641360
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 6aca393d3c804fa3aac0aeaf87d4c289
run_name: stately-foal-634
run_uuid: 6aca393d3c804fa3aac0aeaf87d4c289
source_name: ''
source_type: 4
source_version: ''
start_time: 1746648635973
status: 3
tags: []
user_id: evankellener
