artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/c75a2692d4fb4e13a7e4fcb672f91cdc/artifacts
end_time: 1743977535990
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: c75a2692d4fb4e13a7e4fcb672f91cdc
run_name: enchanting-crab-61
run_uuid: c75a2692d4fb4e13a7e4fcb672f91cdc
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977524406
status: 3
tags: []
user_id: evankellener
