artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/97f70545b4f64fcdbbbee7d4effcc7a0/artifacts
end_time: 1746648602999
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 97f70545b4f64fcdbbbee7d4effcc7a0
run_name: handsome-stork-978
run_uuid: 97f70545b4f64fcdbbbee7d4effcc7a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1746648597122
status: 3
tags: []
user_id: evankellener
