artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/4f8ba6593e2144dfafaab94fcb878f4f/artifacts
end_time: 1743977866353
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 4f8ba6593e2144dfafaab94fcb878f4f
run_name: grandiose-hog-939
run_uuid: 4f8ba6593e2144dfafaab94fcb878f4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977860392
status: 3
tags: []
user_id: evankellener
