artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/eb09c07afaeb4a4eadc890a6900829ff/artifacts
end_time: 1747937031527
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: eb09c07afaeb4a4eadc890a6900829ff
run_name: grandiose-hog-939
run_uuid: eb09c07afaeb4a4eadc890a6900829ff
source_name: ''
source_type: 4
source_version: ''
start_time: 1747937024650
status: 3
tags: []
user_id: evankellener
