artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/adba450f1f4841beadedcecefee79433/artifacts
end_time: 1747943088252
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: adba450f1f4841beadedcecefee79433
run_name: handsome-stork-978
run_uuid: adba450f1f4841beadedcecefee79433
source_name: ''
source_type: 4
source_version: ''
start_time: 1747943071941
status: 3
tags: []
user_id: evankellener
