artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/5e05feffce2746e9ac8dbc6913f85ee9/artifacts
end_time: 1746641382294
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 5e05feffce2746e9ac8dbc6913f85ee9
run_name: amazing-lark-886
run_uuid: 5e05feffce2746e9ac8dbc6913f85ee9
source_name: ''
source_type: 4
source_version: ''
start_time: 1746641376049
status: 3
tags: []
user_id: evankellener
