artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/d6f08ac2f6ea4dcda420752b90e5a8ce/artifacts
end_time: 1743980755289
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: d6f08ac2f6ea4dcda420752b90e5a8ce
run_name: incongruous-dog-687
run_uuid: d6f08ac2f6ea4dcda420752b90e5a8ce
source_name: ''
source_type: 4
source_version: ''
start_time: 1743980751820
status: 3
tags: []
user_id: evankellener
