artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/7ef2a0a2feac4bb0a108ae10f0cd93b7/artifacts
end_time: 1745605322013
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 7ef2a0a2feac4bb0a108ae10f0cd93b7
run_name: dashing-tern-986
run_uuid: 7ef2a0a2feac4bb0a108ae10f0cd93b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1745605313863
status: 3
tags: []
user_id: evankellener
