artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/24bd2cf245b543e4b7b6147acacfcab2/artifacts
end_time: 1748497319171
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 24bd2cf245b543e4b7b6147acacfcab2
run_name: funny-lynx-488
run_uuid: 24bd2cf245b543e4b7b6147acacfcab2
source_name: ''
source_type: 4
source_version: ''
start_time: 1748497316181
status: 3
tags: []
user_id: evankellener
