artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/ec25bb8cf6994bc79bdc8e25b22be2c6/artifacts
end_time: 1748497316087
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: ec25bb8cf6994bc79bdc8e25b22be2c6
run_name: aged-rook-757
run_uuid: ec25bb8cf6994bc79bdc8e25b22be2c6
source_name: ''
source_type: 4
source_version: ''
start_time: 1748497309404
status: 3
tags: []
user_id: evankellener
