artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/0889d9ebd17e44e2baaece2bc25c44a1/artifacts
end_time: 1743980475930
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 0889d9ebd17e44e2baaece2bc25c44a1
run_name: popular-pug-452
run_uuid: 0889d9ebd17e44e2baaece2bc25c44a1
source_name: ''
source_type: 4
source_version: ''
start_time: 1743980470469
status: 3
tags: []
user_id: evankellener
