artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/ca2c5f8ba3304f1fb6cc7d17ba4b6adf/artifacts
end_time: 1746420233756
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: ca2c5f8ba3304f1fb6cc7d17ba4b6adf
run_name: grandiose-hog-939
run_uuid: ca2c5f8ba3304f1fb6cc7d17ba4b6adf
source_name: ''
source_type: 4
source_version: ''
start_time: 1746420227593
status: 3
tags: []
user_id: evankellener
