artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/6eef39dda4cd4d4bb7eeaaf0c126170a/artifacts
end_time: 1743542287978
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 6eef39dda4cd4d4bb7eeaaf0c126170a
run_name: aged-rook-757
run_uuid: 6eef39dda4cd4d4bb7eeaaf0c126170a
source_name: ''
source_type: 4
source_version: ''
start_time: 1743542277494
status: 3
tags: []
user_id: evankellener
