artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/f4c4da1cf5be4b1ca7014809dded302e/artifacts
end_time: 1743977543287
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: f4c4da1cf5be4b1ca7014809dded302e
run_name: fortunate-midge-41
run_uuid: f4c4da1cf5be4b1ca7014809dded302e
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977540897
status: 3
tags: []
user_id: evankellener
