artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/9cee0ff05f0a4eb586bf0ad290f11bee/artifacts
end_time: 1747937120937
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 9cee0ff05f0a4eb586bf0ad290f11bee
run_name: fortunate-midge-41
run_uuid: 9cee0ff05f0a4eb586bf0ad290f11bee
source_name: ''
source_type: 4
source_version: ''
start_time: 1747937114673
status: 3
tags: []
user_id: evankellener
