artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/4a6d4e040ac448bbb9ccdedc90ace1f4/artifacts
end_time: 1744052313535
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 4a6d4e040ac448bbb9ccdedc90ace1f4
run_name: incongruous-hare-938
run_uuid: 4a6d4e040ac448bbb9ccdedc90ace1f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052308161
status: 3
tags: []
user_id: evankellener
