artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/0eea4982e0a349f0befaaeb11db85f38/artifacts
end_time: 1744052051675
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 0eea4982e0a349f0befaaeb11db85f38
run_name: handsome-stork-978
run_uuid: 0eea4982e0a349f0befaaeb11db85f38
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052045815
status: 3
tags: []
user_id: evankellener
