artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/4f90f903caab4b50b0e9cf8daed8f436/artifacts
end_time: 1746729574640
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 4f90f903caab4b50b0e9cf8daed8f436
run_name: thoughtful-wren-332
run_uuid: 4f90f903caab4b50b0e9cf8daed8f436
source_name: ''
source_type: 4
source_version: ''
start_time: 1746729568336
status: 3
tags: []
user_id: evankellener
