artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/2dabfc16593c47b2ad9c5c2fa06eb3f3/artifacts
end_time: 1748497453349
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 2dabfc16593c47b2ad9c5c2fa06eb3f3
run_name: worried-smelt-761
run_uuid: 2dabfc16593c47b2ad9c5c2fa06eb3f3
source_name: ''
source_type: 4
source_version: ''
start_time: 1748497444435
status: 3
tags: []
user_id: evankellener
