artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/56ac6bb4815c4e9cb5b31b1e3cb3ce1a/artifacts
end_time: 1746648543355
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 56ac6bb4815c4e9cb5b31b1e3cb3ce1a
run_name: intrigued-loon-863
run_uuid: 56ac6bb4815c4e9cb5b31b1e3cb3ce1a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746648537105
status: 3
tags: []
user_id: evankellener
