artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/20ad8ed5ce3f4aa4a5df7014bbedaefd/artifacts
end_time: 1748497501443
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 20ad8ed5ce3f4aa4a5df7014bbedaefd
run_name: sneaky-bear-933
run_uuid: 20ad8ed5ce3f4aa4a5df7014bbedaefd
source_name: ''
source_type: 4
source_version: ''
start_time: 1748497497578
status: 3
tags: []
user_id: evankellener
