artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/ccbbdc8ecbc7487eb38f626a9d3cf855/artifacts
end_time: 1744052308063
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: ccbbdc8ecbc7487eb38f626a9d3cf855
run_name: ambitious-ox-510
run_uuid: ccbbdc8ecbc7487eb38f626a9d3cf855
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052301687
status: 3
tags: []
user_id: evankellener
