artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/3cf0a529aee243e2b687fefdcf659ca1/artifacts
end_time: 1746727414161
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 3cf0a529aee243e2b687fefdcf659ca1
run_name: adaptable-bug-798
run_uuid: 3cf0a529aee243e2b687fefdcf659ca1
source_name: ''
source_type: 4
source_version: ''
start_time: 1746727403781
status: 3
tags: []
user_id: evankellener
