artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/de2707287b21476ca0efdb2bfec7abd8/artifacts
end_time: 1746729714349
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: de2707287b21476ca0efdb2bfec7abd8
run_name: rogue-shrike-526
run_uuid: de2707287b21476ca0efdb2bfec7abd8
source_name: ''
source_type: 4
source_version: ''
start_time: 1746729708051
status: 3
tags: []
user_id: evankellener
