artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/d6ab44a2b2634f2dbefc40ea8df348bc/artifacts
end_time: 1743542302893
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: d6ab44a2b2634f2dbefc40ea8df348bc
run_name: big-swan-262
run_uuid: d6ab44a2b2634f2dbefc40ea8df348bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1743542292726
status: 3
tags: []
user_id: evankellener
