artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/b28ee63c1e634cc3bf7820ced685afcd/artifacts
end_time: 1744052169761
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: b28ee63c1e634cc3bf7820ced685afcd
run_name: monumental-bee-165
run_uuid: b28ee63c1e634cc3bf7820ced685afcd
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052160357
status: 3
tags: []
user_id: evankellener
