artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/64eb9b7cbbb14b14a288b652a6e7b4cf/artifacts
end_time: 1744052487855
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 64eb9b7cbbb14b14a288b652a6e7b4cf
run_name: incongruous-dog-687
run_uuid: 64eb9b7cbbb14b14a288b652a6e7b4cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052471739
status: 3
tags: []
user_id: evankellener
