artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/c1ee5d0696f74834a3ecf4cb0ddc6d7d/artifacts
end_time: 1743977687435
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: c1ee5d0696f74834a3ecf4cb0ddc6d7d
run_name: dashing-squid-561
run_uuid: c1ee5d0696f74834a3ecf4cb0ddc6d7d
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977682191
status: 3
tags: []
user_id: evankellener
