artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/a6f5fd78d82c4d16a70ac82fa27de63e/artifacts
end_time: 1743977682088
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: a6f5fd78d82c4d16a70ac82fa27de63e
run_name: respected-smelt-895
run_uuid: a6f5fd78d82c4d16a70ac82fa27de63e
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977679692
status: 3
tags: []
user_id: evankellener
