artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/c3ceba3f8c5c4afe820f853313abb80f/artifacts
end_time: 1748497147856
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: c3ceba3f8c5c4afe820f853313abb80f
run_name: popular-pug-452
run_uuid: c3ceba3f8c5c4afe820f853313abb80f
source_name: ''
source_type: 4
source_version: ''
start_time: 1748497140437
status: 3
tags: []
user_id: evankellener
