artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/fec5cdb614cb4b10aefbb8e09ee54871/artifacts
end_time: 1743542158565
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: fec5cdb614cb4b10aefbb8e09ee54871
run_name: handsome-stork-978
run_uuid: fec5cdb614cb4b10aefbb8e09ee54871
source_name: ''
source_type: 4
source_version: ''
start_time: 1743542151882
status: 3
tags: []
user_id: evankellener
