artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/748eeca5ced24e16b084c7d0ec8bd740/artifacts
end_time: 1743534778761
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 748eeca5ced24e16b084c7d0ec8bd740
run_name: incongruous-dog-687
run_uuid: 748eeca5ced24e16b084c7d0ec8bd740
source_name: ''
source_type: 4
source_version: ''
start_time: 1743534776776
status: 3
tags: []
user_id: evankellener
