artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/abed0ecdc928440cab08ac403c235eef/artifacts
end_time: 1747937037164
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: abed0ecdc928440cab08ac403c235eef
run_name: nervous-snipe-157
run_uuid: abed0ecdc928440cab08ac403c235eef
source_name: ''
source_type: 4
source_version: ''
start_time: 1747937035271
status: 3
tags: []
user_id: evankellener
