artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/29b4b368cd5842e99bdac2ddf1da93db/artifacts
end_time: 1744052203169
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 29b4b368cd5842e99bdac2ddf1da93db
run_name: youthful-moth-618
run_uuid: 29b4b368cd5842e99bdac2ddf1da93db
source_name: ''
source_type: 4
source_version: ''
start_time: 1744052187502
status: 3
tags: []
user_id: evankellener
