artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/e9fc082e66064bb7a5bfbba9b333c71d/artifacts
end_time: 1746727542676
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: e9fc082e66064bb7a5bfbba9b333c71d
run_name: entertaining-ape-728
run_uuid: e9fc082e66064bb7a5bfbba9b333c71d
source_name: ''
source_type: 4
source_version: ''
start_time: 1746727533557
status: 3
tags: []
user_id: evankellener
