artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/f5f5fa89438b42948e0fbdcf2e1cc1a4/artifacts
end_time: 1743528337591
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: f5f5fa89438b42948e0fbdcf2e1cc1a4
run_name: enchanting-crab-61
run_uuid: f5f5fa89438b42948e0fbdcf2e1cc1a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1743528336015
status: 3
tags: []
user_id: evankellener
