artifact_uri: /Users/evankellener/Desktop/UFC_fight_predictor/saved_models/111226803126281266/29accbdf44684bdbb5a00cdda1e9b25b/artifacts
end_time: 1743978001722
entry_point_name: ''
experiment_id: '111226803126281266'
lifecycle_stage: active
run_id: 29accbdf44684bdbb5a00cdda1e9b25b
run_name: magnificent-foal-220
run_uuid: 29accbdf44684bdbb5a00cdda1e9b25b
source_name: ''
source_type: 4
source_version: ''
start_time: 1743977996763
status: 3
tags: []
user_id: evankellener
